package com.surgicalcopilot.service;

import com.surgicalcopilot.entity.VitalSign;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Real-Time Emergency Detection.
 *
 * Real (non-simulated) threshold-based alerting against vitals data
 * (which is itself simulated/synthetic, generated by VitalsSimulationService).
 * The alerting logic itself is genuine - simple, transparent, clinically
 * reasonable thresholds, not a trained model. Real systems would use
 * validated early-warning scores (e.g. NEWS2) and real device integration.
 */
@Service
public class EmergencyDetectionService {

    public List<Map<String, String>> evaluate(VitalSign v) {
        List<Map<String, String>> alerts = new ArrayList<>();
        if (v == null) return alerts;

        if (v.getHeartRateBpm() != null && (v.getHeartRateBpm() > 130 || v.getHeartRateBpm() < 45)) {
            alerts.add(Map.of("level", "HIGH", "message", "Heart rate out of safe range: " + v.getHeartRateBpm() + " bpm"));
        }
        if (v.getOxygenSaturationPct() != null && v.getOxygenSaturationPct() < 90) {
            alerts.add(Map.of("level", "HIGH", "message", "Low oxygen saturation: " + v.getOxygenSaturationPct() + "%"));
        }
        if (v.getSystolicBp() != null && (v.getSystolicBp() > 180 || v.getSystolicBp() < 90)) {
            alerts.add(Map.of("level", "MEDIUM", "message", "Blood pressure out of typical range: " + v.getSystolicBp() + " systolic"));
        }
        if (v.getTemperatureCelsius() != null && v.getTemperatureCelsius() >= 39.0) {
            alerts.add(Map.of("level", "MEDIUM", "message", "High temperature: " + v.getTemperatureCelsius() + "°C"));
        }
        if (v.getRespiratoryRate() != null && (v.getRespiratoryRate() > 24 || v.getRespiratoryRate() < 10)) {
            alerts.add(Map.of("level", "MEDIUM", "message", "Respiratory rate out of typical range: " + v.getRespiratoryRate() + "/min"));
        }

        return alerts;
    }
}
