import { useEffect, useState } from 'react'
import { RefreshCw } from 'lucide-react'
import { getSurgeries, recomputePrediction, getPatients, getDoctors, createSurgery } from '../services/api'
import StatusBadge from '../components/StatusBadge'
import SimulatedBanner from '../components/SimulatedBanner'

const EMPTY = { patientId: '', doctorId: '', procedureName: '', procedureType: 'GENERAL' }

export default function SuccessPrediction() {
  const [surgeries, setSurgeries] = useState([])
  const [patients, setPatients] = useState([])
  const [doctors, setDoctors] = useState([])
  const [form, setForm] = useState(EMPTY)
  const [showForm, setShowForm] = useState(false)

  const load = () => getSurgeries().then((res) => setSurgeries(res.data)).catch(() => {})

  useEffect(() => {
    load()
    getPatients().then((res) => setPatients(res.data)).catch(() => {})
    getDoctors().then((res) => setDoctors(res.data)).catch(() => {})
  }, [])

  const handleSubmit = async (e) => {
    e.preventDefault()
    await createSurgery({
      patient: { id: form.patientId },
      leadSurgeon: form.doctorId ? { id: form.doctorId } : null,
      procedureName: form.procedureName,
      procedureType: form.procedureType,
      status: 'SCHEDULED',
    })
    setForm(EMPTY)
    setShowForm(false)
    load()
  }

  const handleRecompute = async (id) => {
    await recomputePrediction(id)
    load()
  }

  return (
    <div className="page-container">
      <div className="page-header">
        <div className="page-eyebrow">CORE SURGICAL INTELLIGENCE</div>
        <h1 className="page-title">Surgery Success Prediction</h1>
        <p className="page-description">Simulated estimate of procedure success likelihood, blood loss, and duration.</p>
        <div style={{ marginTop: 10 }}><StatusBadge status="LIVE_DEMO" /></div>
      </div>

      <SimulatedBanner>
        These predictions are generated by a simple heuristic with randomized variation by
        procedure type — <strong>not a trained clinical model</strong>. Real surgical risk
        prediction requires validated models built on real outcome data.
      </SimulatedBanner>

      <button className="btn btn-primary" style={{ marginBottom: 16 }} onClick={() => setShowForm(!showForm)}>
        New surgery
      </button>

      {showForm && (
        <form className="card" onSubmit={handleSubmit} style={{ marginBottom: 20 }}>
          <div className="form-row">
            <div className="form-field">
              <label>Patient *</label>
              <select required value={form.patientId} onChange={(e) => setForm({ ...form, patientId: e.target.value })}>
                <option value="">Select</option>
                {patients.map((p) => <option key={p.id} value={p.id}>{p.fullName}</option>)}
              </select>
            </div>
            <div className="form-field">
              <label>Lead surgeon</label>
              <select value={form.doctorId} onChange={(e) => setForm({ ...form, doctorId: e.target.value })}>
                <option value="">Select</option>
                {doctors.map((d) => <option key={d.id} value={d.id}>{d.fullName}</option>)}
              </select>
            </div>
          </div>
          <div className="form-row">
            <div className="form-field">
              <label>Procedure name *</label>
              <input required value={form.procedureName} onChange={(e) => setForm({ ...form, procedureName: e.target.value })} />
            </div>
            <div className="form-field">
              <label>Procedure type</label>
              <select value={form.procedureType} onChange={(e) => setForm({ ...form, procedureType: e.target.value })}>
                <option value="GENERAL">General</option>
                <option value="CARDIAC">Cardiac</option>
                <option value="NEURO">Neuro</option>
                <option value="ORTHOPEDIC">Orthopedic</option>
                <option value="TRANSPLANT">Transplant</option>
              </select>
            </div>
          </div>
          <button className="btn btn-primary" type="submit">Create &amp; predict</button>
        </form>
      )}

      <div className="card">
        {surgeries.length === 0 ? <div className="empty-state">No surgeries yet.</div> : (
          <table className="data-table">
            <thead><tr><th>Procedure</th><th>Patient</th><th>Predicted success</th><th>Est. duration</th><th></th></tr></thead>
            <tbody>
              {surgeries.map((s) => (
                <tr key={s.id}>
                  <td>{s.procedureName}</td>
                  <td>{s.patient?.fullName}</td>
                  <td style={{ fontFamily: 'var(--font-mono)', color: 'var(--signal-cyan)' }}>{s.predictedSuccessRate}%</td>
                  <td>{s.predictedDurationMinutes} min</td>
                  <td><button className="btn btn-secondary" onClick={() => handleRecompute(s.id)}><RefreshCw size={13} /></button></td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  )
}
